name: flutter_adsense_web
description: A Flutter web package to easily integrate Google AdSense banner ads.
version: 0.0.1
homepage: https://github.com/your-username/adsense_flutter_web

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.2.4
